// GENERATED by shared/seed/generate.ts. Do not edit by hand.
// One slice of shared/billing-seed.json per demo tenant, keyed by phone.
// Each holds a single tenancy and its own company only. In Phase 2 this
// comes from Supabase, scoped to the signed-in tenant by RLS.

const Map<String, String> kTenantSeedsByPhone = {
  '+254733605118': r'''
{
  "asOf": "2026-10-06",
  "companies": [
    {
      "id": "harborridge",
      "slug": "harborridge",
      "name": "HarborRidge Limited",
      "kraPin": "P051234567X",
      "mpesaPaybill": "522533",
      "bankName": "NCBA Bank, Westlands",
      "bankAccount": "1004558231",
      "settings": {
        "ledgerStartMonth": "2026-05",
        "dueDay": 5,
        "graceDay": 20,
        "depositSchedule": {
          "1": 25000,
          "2": 30000
        },
        "recordRetentionMonths": 6
      },
      "sequences": {
        "receipt": 379,
        "repairTicket": 1047
      },
      "subscription": {
        "plan": "growth",
        "status": "active",
        "unitLimit": 100,
        "staffLimit": 10,
        "trialEndsAt": null
      }
    }
  ],
  "properties": [
    {
      "id": "riverside-court",
      "companyId": "harborridge",
      "managerId": "s-njoki",
      "name": "Riverside Court",
      "type": "apartments",
      "address": "Riverside Dr, Westlands",
      "accountPrefix": "RC",
      "waterRate": 150,
      "garbageFee": 250,
      "rateHistory": [
        {
          "from": "2026-05",
          "waterRate": 150,
          "garbageFee": 250
        }
      ]
    }
  ],
  "units": [
    {
      "id": "rc-5a",
      "propertyId": "riverside-court",
      "label": "5A",
      "bedrooms": 2
    }
  ],
  "tenants": [
    {
      "id": "t-david",
      "companyId": "harborridge",
      "name": "David Mwangi",
      "phone": "0733 605 118",
      "email": "david.mwangi@example.com"
    }
  ],
  "tenancies": [
    {
      "openingBalance": 0,
      "openingReading": null,
      "moveOut": null,
      "renewal": {
        "leaseId": "L-2231",
        "rent": 31500,
        "start": "2026-11-01",
        "end": "2027-10-31",
        "status": "Awaiting signature"
      },
      "moveOutNote": null,
      "depositRefund": null,
      "id": "L-2160",
      "tenantId": "t-david",
      "unitId": "rc-5a",
      "rent": 30000,
      "deposit": 30000,
      "moveIn": "2025-11-01",
      "leaseStart": "2025-11-01",
      "leaseEnd": "2026-10-31"
    }
  ],
  "meterReadings": {
    "rc-5a": {
      "2026-04": 276,
      "2026-05": 287,
      "2026-06": 305,
      "2026-07": 313,
      "2026-08": 324,
      "2026-09": 332,
      "2026-10": 347
    }
  },
  "payments": [
    {
      "receiptNumber": "RCT-2605-0306",
      "tenancyId": "L-2160",
      "amount": 31900,
      "date": "2026-05-02",
      "time": "16:05",
      "method": "M-Pesa",
      "reference": "SQWESR3DFP"
    },
    {
      "receiptNumber": "RCT-2606-0320",
      "tenancyId": "L-2160",
      "amount": 32950,
      "date": "2026-06-02",
      "time": "13:14",
      "method": "M-Pesa",
      "reference": "SK5HHPMY5L"
    },
    {
      "receiptNumber": "RCT-2607-0336",
      "tenancyId": "L-2160",
      "amount": 31450,
      "date": "2026-07-02",
      "time": "16:16",
      "method": "M-Pesa",
      "reference": "SC15RBEZN2"
    },
    {
      "receiptNumber": "RCT-2608-0355",
      "tenancyId": "L-2160",
      "amount": 31900,
      "date": "2026-08-04",
      "time": "17:02",
      "method": "Bank",
      "reference": "FT2608048230"
    },
    {
      "receiptNumber": "RCT-2609-0365",
      "tenancyId": "L-2160",
      "amount": 30000,
      "date": "2026-09-03",
      "time": "15:10",
      "method": "M-Pesa",
      "reference": "SAGB3A477F"
    },
    {
      "receiptNumber": "RCT-2610-0373",
      "tenancyId": "L-2160",
      "amount": 15000,
      "date": "2026-10-02",
      "time": "10:21",
      "method": "M-Pesa",
      "reference": "SWULAPG9YP"
    }
  ],
  "staff": [
    {
      "id": "s-njoki",
      "companyId": "harborridge",
      "name": "Njoki Kariuki",
      "role": "manager",
      "phone": "0711 000 222",
      "propertyIds": []
    }
  ],
  "repairTickets": [
    {
      "companyId": "harborridge",
      "unitId": "rc-5a",
      "id": "MT-1039",
      "tenancyId": "L-2160",
      "category": "electrical",
      "priority": "high",
      "status": "resolved",
      "title": "Socket in bedroom sparks",
      "description": "The socket by the bed sparks when anything is plugged in.",
      "hasPhoto": true,
      "createdAt": "2026-09-22T21:10:00+03:00",
      "resolvedAt": "2026-09-24T11:00:00+03:00",
      "assignedTo": "Otieno Fundi Services",
      "resolutionNote": "Socket and faceplate replaced."
    }
  ],
  "messages": [
    {
      "companyId": "harborridge",
      "id": "msg-201",
      "tenancyId": "L-2160",
      "sender": "tenant",
      "staffId": null,
      "body": "I sent the renewal back with a question about the 5% increase. Can we discuss?",
      "sentAt": "2026-10-05T18:20:00+03:00",
      "readByStaffAt": "2026-10-06T09:05:00+03:00"
    },
    {
      "companyId": "harborridge",
      "id": "msg-202",
      "tenancyId": "L-2160",
      "sender": "staff",
      "staffId": "s-njoki",
      "body": "Hi David, the increase matches the market review for Riverside Court. Happy to keep the deposit as is so nothing extra is due.",
      "sentAt": "2026-10-06T09:12:00+03:00",
      "readByStaffAt": null
    }
  ]
}
''',
  '+254723555019': r'''
{
  "asOf": "2026-10-06",
  "companies": [
    {
      "id": "savanna",
      "slug": "savanna",
      "name": "Savanna Homes Ltd",
      "kraPin": "P052765431Q",
      "mpesaPaybill": "400200",
      "bankName": "Equity Bank, Nakuru",
      "bankAccount": "0170299934455",
      "settings": {
        "ledgerStartMonth": "2026-07",
        "dueDay": 1,
        "graceDay": 10,
        "depositSchedule": {
          "1": 15000,
          "2": 20000
        },
        "recordRetentionMonths": 12
      },
      "sequences": {
        "receipt": 115,
        "repairTicket": 2002
      },
      "subscription": {
        "plan": "starter",
        "status": "trial",
        "unitLimit": 20,
        "staffLimit": 3,
        "trialEndsAt": "2026-10-31"
      }
    }
  ],
  "properties": [
    {
      "id": "milimani-court",
      "companyId": "savanna",
      "managerId": "s-wanjiru",
      "name": "Milimani Court",
      "type": "apartments",
      "address": "Milimani, Nakuru",
      "accountPrefix": "MC",
      "waterRate": 120,
      "garbageFee": 200,
      "rateHistory": [
        {
          "from": "2026-07",
          "waterRate": 120,
          "garbageFee": 200
        }
      ]
    }
  ],
  "units": [
    {
      "id": "mc-3",
      "propertyId": "milimani-court",
      "label": "3",
      "bedrooms": 2
    }
  ],
  "tenants": [
    {
      "id": "t-naliaka",
      "companyId": "savanna",
      "name": "Naliaka Wekesa",
      "phone": "0723 555 019",
      "email": "naliaka.wekesa@example.com"
    }
  ],
  "tenancies": [
    {
      "openingBalance": 0,
      "openingReading": null,
      "moveOut": null,
      "renewal": null,
      "moveOutNote": null,
      "depositRefund": null,
      "id": "SV-102",
      "tenantId": "t-naliaka",
      "unitId": "mc-3",
      "rent": 18000,
      "deposit": 20000,
      "moveIn": "2026-01-01",
      "leaseStart": "2026-01-01",
      "leaseEnd": "2026-12-31"
    }
  ],
  "meterReadings": {
    "mc-3": {
      "2026-06": 228,
      "2026-07": 237,
      "2026-08": 247,
      "2026-09": 266,
      "2026-10": 279
    }
  },
  "payments": [
    {
      "receiptNumber": "RCT-2607-0103",
      "tenancyId": "SV-102",
      "amount": 19280,
      "date": "2026-07-01",
      "time": "17:36",
      "method": "M-Pesa",
      "reference": "SBCQ50N65U"
    },
    {
      "receiptNumber": "RCT-2608-0106",
      "tenancyId": "SV-102",
      "amount": 19400,
      "date": "2026-08-01",
      "time": "19:09",
      "method": "M-Pesa",
      "reference": "SXPFKK8LJB"
    },
    {
      "receiptNumber": "RCT-2609-0112",
      "tenancyId": "SV-102",
      "amount": 20480,
      "date": "2026-09-01",
      "time": "20:29",
      "method": "M-Pesa",
      "reference": "SJS5FR1974"
    },
    {
      "receiptNumber": "RCT-2610-0115",
      "tenancyId": "SV-102",
      "amount": 8000,
      "date": "2026-10-03",
      "time": "13:30",
      "method": "M-Pesa",
      "reference": "SM6Q6JL1YG"
    }
  ],
  "staff": [
    {
      "id": "s-wanjiru",
      "companyId": "savanna",
      "name": "Wanjiru Maina",
      "role": "manager",
      "phone": "0711 600 101",
      "propertyIds": []
    }
  ],
  "repairTickets": [
    {
      "companyId": "savanna",
      "unitId": "mc-3",
      "id": "MT-2002",
      "tenancyId": "SV-102",
      "category": "plumbing",
      "priority": "medium",
      "status": "open",
      "title": "Bathroom tap dripping",
      "description": "The bathroom tap drips all night.",
      "hasPhoto": false,
      "createdAt": "2026-10-04T20:15:00+03:00",
      "resolvedAt": null,
      "assignedTo": null,
      "resolutionNote": null
    }
  ],
  "messages": [
    {
      "companyId": "savanna",
      "id": "msg-901",
      "tenancyId": "SV-102",
      "sender": "tenant",
      "staffId": null,
      "body": "Hello, the bathroom tap is dripping all night. Can someone look at it?",
      "sentAt": "2026-10-04T20:16:00+03:00",
      "readByStaffAt": "2026-10-05T08:00:00+03:00"
    },
    {
      "companyId": "savanna",
      "id": "msg-902",
      "tenancyId": "SV-102",
      "sender": "staff",
      "staffId": "s-wanjiru",
      "body": "Hi Naliaka, Kamau will pass by tomorrow morning to fix it.",
      "sentAt": "2026-10-05T08:10:00+03:00",
      "readByStaffAt": null
    }
  ]
}
''',
  '+254720671093': r'''
{
  "asOf": "2026-10-06",
  "companies": [
    {
      "id": "harborridge",
      "slug": "harborridge",
      "name": "HarborRidge Limited",
      "kraPin": "P051234567X",
      "mpesaPaybill": "522533",
      "bankName": "NCBA Bank, Westlands",
      "bankAccount": "1004558231",
      "settings": {
        "ledgerStartMonth": "2026-05",
        "dueDay": 5,
        "graceDay": 20,
        "depositSchedule": {
          "1": 25000,
          "2": 30000
        },
        "recordRetentionMonths": 6
      },
      "sequences": {
        "receipt": 379,
        "repairTicket": 1047
      },
      "subscription": {
        "plan": "growth",
        "status": "active",
        "unitLimit": 100,
        "staffLimit": 10,
        "trialEndsAt": null
      }
    }
  ],
  "properties": [
    {
      "id": "riverside-court",
      "companyId": "harborridge",
      "managerId": "s-njoki",
      "name": "Riverside Court",
      "type": "apartments",
      "address": "Riverside Dr, Westlands",
      "accountPrefix": "RC",
      "waterRate": 150,
      "garbageFee": 250,
      "rateHistory": [
        {
          "from": "2026-05",
          "waterRate": 150,
          "garbageFee": 250
        }
      ]
    }
  ],
  "units": [
    {
      "id": "rc-2a",
      "propertyId": "riverside-court",
      "label": "2A",
      "bedrooms": 2
    }
  ],
  "tenants": [
    {
      "id": "t-joseph",
      "companyId": "harborridge",
      "name": "Joseph Kariuki",
      "phone": "0720 671 093",
      "email": "joseph.kariuki@example.com"
    }
  ],
  "tenancies": [
    {
      "openingBalance": 0,
      "openingReading": null,
      "moveOut": "2026-08-31",
      "renewal": null,
      "moveOutNote": "Unit handed back in good condition. Deposit balance refunded by M-Pesa.",
      "depositRefund": {
        "date": "2026-09-08",
        "method": "M-Pesa",
        "reference": "SH7Q2KD81M"
      },
      "id": "L-2071",
      "tenantId": "t-joseph",
      "unitId": "rc-2a",
      "rent": 30000,
      "deposit": 30000,
      "moveIn": "2025-03-01",
      "leaseStart": "2025-03-01",
      "leaseEnd": "2026-08-31"
    }
  ],
  "meterReadings": {
    "rc-2a": {
      "2026-04": 270,
      "2026-05": 289,
      "2026-06": 300,
      "2026-07": 308,
      "2026-08": 317,
      "2026-09": 327,
      "2026-10": 327
    }
  },
  "payments": [
    {
      "receiptNumber": "RCT-2605-0301",
      "tenancyId": "L-2071",
      "amount": 33100,
      "date": "2026-05-01",
      "time": "09:44",
      "method": "M-Pesa",
      "reference": "SX46QZG313"
    },
    {
      "receiptNumber": "RCT-2606-0316",
      "tenancyId": "L-2071",
      "amount": 31900,
      "date": "2026-06-01",
      "time": "12:02",
      "method": "M-Pesa",
      "reference": "SNMPDSCFUP"
    },
    {
      "receiptNumber": "RCT-2607-0331",
      "tenancyId": "L-2071",
      "amount": 31450,
      "date": "2026-07-01",
      "time": "10:43",
      "method": "M-Pesa",
      "reference": "SSWN17PM66"
    },
    {
      "receiptNumber": "RCT-2608-0346",
      "tenancyId": "L-2071",
      "amount": 31600,
      "date": "2026-08-01",
      "time": "19:01",
      "method": "M-Pesa",
      "reference": "SPGKUPD6P5"
    }
  ],
  "staff": [
    {
      "id": "s-njoki",
      "companyId": "harborridge",
      "name": "Njoki Kariuki",
      "role": "manager",
      "phone": "0711 000 222",
      "propertyIds": []
    }
  ],
  "repairTickets": [],
  "messages": []
}
''',
};

/// The slice used when no one has signed in yet (tests, previews).
const String kDefaultTenantPhone = '+254733605118';
